name: Build & Deploy Frontend

on:
  workflow_dispatch:
  push:
    branches: [ "deploy" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependencias y correr pruebas
        run: |
          npm ci
          npm test -- --watch=false --browsers=ChromeHeadless

  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - id: ecr
        name: Login a Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Build & Push Frontend
        env:
          REGISTRY: ${{ steps.ecr.outputs.registry }}
        run: |
          IMAGE=$REGISTRY/casino-frontend
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      - name: Deploy en EC2 Frontend
        uses: appleboy/ssh-action@v1
        env:
          IMAGE: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/casino-frontend:latest
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE
          script: |
            aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
              | docker login --username AWS --password-stdin \
                ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

            docker pull "$IMAGE"

            docker rm -f casino-frontend || true

            docker run -d \
              --name casino-frontend \
              --restart unless-stopped \
              -p 80:8080 \
              -e BACKEND_HOST=${{ secrets.BACKEND_HOST_PRIVATE }} \
              "$IMAGE"

            docker ps
            docker logs --tail 20 casino-frontend